=== Witchen/php-xml-xsl/xml/buyerProfile/buyerProfile.dtd
<!ELEMENT buyerProfile (buyerProfileItem*)>
<!ELEMENT buyerProfileItem (id,full_name,username,mobile_number,email,address,role)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT full_name (#PCDATA)>
<!ELEMENT username (#PCDATA)>
<!ELEMENT mobile_number (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT role (#PCDATA)>

=== Witchen/php-xml-xsl/xml/buyerProfile/buyerProfile.xml
<?xml version="1.0"?>
<!DOCTYPE buyerProfile SYSTEM "buyerProfile.dtd">
<buyerProfile>
  <buyerProfileItem>
    <id>16</id>
    <full_name>buyer1</full_name>
    <username>buyer1</username>
    <mobile_number>123123</mobile_number>
    <email>buyer1@gmail.com</email>
    <address>buyer1buyer1</address>
    <role>buyer</role>
  </buyerProfileItem>
</buyerProfile>
