=== Witchen/php-xml-xsl/xml/reports/reports.dtd
<!ELEMENT reports (tableItem*)>
<!ELEMENT tableItem (id,category,title,stock,price,quantity,revenue)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT category (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT stock (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT quantity (#PCDATA)>
<!ELEMENT revenue (#PCDATA)>

=== Witchen/php-xml-xsl/xml/reports/reports.xml
<?xml version="1.0"?>
<!DOCTYPE reports SYSTEM "reports.dtd">
<reports>
  <tableItem>
    <id>45</id>
    <category>Handphone</category>
    <title>Samsung Galaxy Fold</title>
    <stock>88</stock>
    <price>10000</price>
    <quantity>1</quantity>
    <revenue>10600</revenue>
  </tableItem>
</reports>
