=== Witchen/php-xml-xsl/xml/profile/profile.dtd
<!ELEMENT profile (profileItem*)>
<!ELEMENT profileItem (id,full_name,username,mobile_number,email,address,role,storeName,storeLocation,storeEmail)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT full_name (#PCDATA)>
<!ELEMENT username (#PCDATA)>
<!ELEMENT mobile_number (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT role (#PCDATA)>
<!ELEMENT storeName (#PCDATA)>
<!ELEMENT storeLocation (#PCDATA)>
<!ELEMENT storeEmail (#PCDATA)>

=== Witchen/php-xml-xsl/xml/profile/profile.xml
<?xml version="1.0"?>
<!DOCTYPE profile SYSTEM "profile.dtd">
<profile>
  <profileItem>
    <id>19</id>
    <full_name>NewAcc</full_name>
    <username>NewAcc</username>
    <mobile_number>123123123</mobile_number>
    <email>ariyadhana.sunardi38@gmail.com</email>
    <address>NewAcc</address>
    <role>seller</role>
    <storeName>NewAcc</storeName>
    <storeLocation>widyStore@gmail.com</storeLocation>
    <storeEmail>NewAccNewAcc</storeEmail>
  </profileItem>
</profile>
